### ISSUE TITLE
Rules with multibyte UTF-8 characters do not work right

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#246]
**Describe the bug**
Rules that contain multibyte UTF-8 characters do not behave as you would expect.

**To Reproduce**
Here is a sample file, `utf8rules.yml`:
```
rules:

- name: UTF-8 Test Rule
  id: utf8.1

  # regular single-byte characters work without surprise
  pattern: |
    (?x)
    (
      good\ day
    )

  examples:
  - 'good day'

  negative_examples:
  - 'Good Day!'


# literal utf-8 multibyte characters also seem to work without surprise
- name: UTF-8 Test Rule
  id: utf8.2

  pattern: |
    (?x)
    (
      Güten\ Tag
    )

  examples:
  - 'Güten Tag'

  negative_examples:
  - 'güten Tag'


# When you use the case-insensitive (?i) flag, utf-8 multibyte characters DON'T
# work as you expect; presumably the single bytes of the `ü` are individually
# handled case-insensitively, which is the wrong thing
- name: UTF-8 Test Rule
  id: utf8.3

  pattern: |
    (?x)(?i)
    (
      Güten\ Tag
    )

  examples:
  - 'Güten Tag'
  - 'güten tag'

  negative_examples:
  # one would like this to actually match, but the (?i) flag doesn't interact
  # properly with multibyte characters in Nosey Parker
  - 'GÜTEN TAG'


# You can explicitly specify different multibyte UTF-8 characters using regex
# alternation, so as to verbosely approximate case-insensitivity.
# But you have to use regex alternation, not character classes, to avoid a
# Vectorscan error about `Unicode not allowed here`.
- name: UTF-8 Test Rule
  id: utf8.4

  pattern: |
    (?x)(?i)
    (
      G (?: ü | Ü ) ten\ Tag
    )

  examples:
  - 'Güten Tag'
  - 'güten tag'
  - 'GÜTEN TAG'


rulesets:

- name: UTF-8 Tests
  description: 'Tests for UTF-8 rule and input handling'
  id: utf8

  include_rule_ids:
  - utf8.1
  - utf8.2
  - utf8.3
  - utf8.4
```

Validate with `noseyparker rules check --rules-path utf8rules.yml`

**Expected behavior**
Multibyte UTF-8 sequences would work as expected in all pattern contexts (character classes, etc), without surprise.

**Actual behavior**
A bunch of workarounds are required.

**Output of `noseyparker --version`**
This applies to all versions of Nosey Parker
